--- #YAML:1.0
name:               Spreadsheet-XML_to_XLS
version:            0.02
abstract:           ~
author:
    - Radik Usmanov (radik.usmanov@ubs.com, rusmanov@luxoft.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Spreadsheet::WriteExcel:  2.37
    XML::DOM:             1.44
requires:
    Spreadsheet::WriteExcel:  2.37
    XML::DOM:             1.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
